language: python
cache: pip
services:
  - docker
python:
  - "3.6"
  - "3.6-dev"
  - "3.7"
  - "3.7-dev"
  - "3.8"
  - "3.8-dev"
  - "3.9-dev"
  # - "nightly"
before_install:
  - pip install -U pip
  - pip install -U setuptools wheel
install:
  - pip install -Ur requirements.txt
  - pip install -U flake8 pylint pytest-cov codecov
  - docker pull gcc:4.9
script:
  - flake8 dockerjudge
  - pylint dockerjudge
  - pytest --cov=.
after_script:
  - codecov
