language: python
cache: pip
services:
  - docker
python:
  - "3.6"
  - "3.6-dev"
  - "3.7"
  - "3.7-dev"
  - "3.8"
  - "3.8-dev"
  - "3.9-dev"
  # - "nightly"
before_install:
  - pip install -U pip
  - pip install -U setuptools wheel
install:
  - pip install -Ur requirements.txt
  - pip install -U flake8 pylint pytest-cov codecov
  - docker pull gcc:4.8  # For gcc & g++
  - docker pull gcc:4.9  # For gccgo
  - docker pull golang:1  # For go
  - docker pull python:3  # For python3
  - docker pull python:2  # For python2
  - docker pull node:12  # For node
  - docker pull openjdk  # For javac and java
script:
  - flake8 dockerjudge
  - pylint dockerjudge
  - pytest --cov=.
after_script:
  - codecov
