language: python
cache: pip
services:
  - docker
python:
  - "3.6"
  - "3.6-dev"
  - "3.7"
  - "3.7-dev"
  - "3.8"
  - "3.8-dev"
  - "3.9-dev"
  - "nightly"
before_install:
  - pip install -U pip
  - pip install -U setuptools wheel
install:
  - make pip
  - pip install -U tox flake8 pylint pytest-cov codecov
  - make docker-pull
script:
  - make flake8
  - make pylint
  - make pytest
  - make tox
after_script:
  - codecov
